a=int(input("Enter First Number : "))
b=int(input("Enter Second Number : "))
print("\n=== Inputs Entered === \n")
print("First number entered is : ", a)
print("Second number entered is : ", b)
print("\n=== Arithemetic Results === \n")
print(f"Addition : {a+b}")
print(f"Subtraction :  {a-b}")
print(f"Multiplication :  {a*b}")
print(f"Division : {a/b}")
print(f"Floor Division :  {a//b}")
print(f"Modulus : {a%b}")
print(f"Power : {a**b}")
print("\n=*=*=*=*=*=*=*=*=*=*= \n")

